name: Consolidate Documentation and Create Pull Request

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  # schedule:
  #   - cron: '0 0 * * 1' # Runs weekly on Monday at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  consolidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to detect changes

      - name: Checkout Terraform Source Repository
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform
          path: terraform-source
          ref: main

      - name: Checkout AWS Provider Source Repository
        uses: actions/checkout@v3
        with:
          repository: hashicorp/terraform-provider-aws
          path: aws-provider-source
          ref: main

      - name: Copy Documentation Folders
        run: |
          mkdir -p language
          cp -r terraform-source/website/docs/language/* language/
          mkdir -p aws-provider
          cp -r aws-provider-source/website/docs/* aws-provider/

      - name: Clean up
        run: |
          rm -rf terraform-source
          rm -rf aws-provider-source
          rm -rf aws-provider/cdktf

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if ! git diff-index --quiet HEAD --; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Set branch name with date
        id: set_branch_name
        run: echo "::set-output name=branch_name::consolidate-docs-$(date +'%Y-%m-%d')"
  
      - name: Create Pull Request if changes are present
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.set_branch_name.outputs.branch_name }} # Branch name for the pull request, now includes date
          base: main
          title: 'Documentation Consolidation Update'
          body: 'Automated update of documentation folders from source repositories.'
          commit-message: 'Consolidate documentation folders'
